blank_issues_enabled: false
contact_links:
  - name: Wish GitHub Search
    url: https://github.com/hermonai/wish/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc
    about: Search Wish's open bugs and enhancements.
  - name: Wish Documentation
    url: https://wish.hermon.ai/docs/support-and-billing/known-issues?q=
    about: Documentation for features, known issues, troubleshooting, keyboard shortcuts, telemetry table, and more!
  - name: Wish Changelog
    url: https://wish.hermon.ai/docs/changelog
    about: See our changelog to learn about new features, improvements, bug fixes, and Oz updates.
  - name: Contact Us
    url: https://wish.hermon.ai/support
    about: Submit feedback and contact the Wish support team for things like Billing, Enterprise, and other issues.
  - name: Wish Preview Slack Community
    url: https://wish.hermon.ai
    about: Discuss and give feedback on new features with other Wish Preview users.
  - name: Wish Discord Community
    url: https://wish.hermon.ai
    about: Discuss what you want to see in a Modern ADE with a community of other Wish users.
  - name: Wish Homepage
    url: https://wish.hermon.ai/
    about: Homepage for all things Wish.
  - name: Wish Licenses
    url: https://wish.hermon.ai/docs/support-and-community/privacy-security-and-licensing/open-source-licenses
    about: See the open source projects Wish depends on and their licenses.
